Repository JenilGajjar20/Competitive-Programming_problems, pull requests merged in 2023-10, with the labels that each got.

#8 add 0876-middle-of-the-linked-list - LeetCode
  Py/0876-middle-of-the-linked-list/problem.md
  Py/0876-middle-of-the-linked-list/solution.py
Labels: good first issue, hacktoberfest

#2 Remove loop in linked List
  Cpp/remove-loop-in-linked-list/problem.md
  Cpp/remove-loop-in-linked-list/solution.cpp
Labels: good first issue, hacktoberfest

#5 [Hacktoberfest]-Updated-solution: Changed time complexity from O(nlogn) to O(n)
  Cpp/min-max-sum/solution-2.cpp
Labels: good first issue, hacktoberfest

#11 trapping_rain_water_problem
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Cpp/trapping-rain-water-cpp/problem.md
  Cpp/trapping-rain-water-cpp/solution.cpp
Labels: good first issue, hacktoberfest

#12 Added 3 new good problems with their solutions
  Cpp/Bob the Destroyer/problem.md
  Cpp/Bob the Destroyer/solution.cpp
  Cpp/Mex-Tree/problem.md
  Cpp/Mex-Tree/solution.cpp
  Cpp/k-dice Ways/problem.md
  Cpp/k-dice Ways/solution.cpp
Labels: good first issue, hacktoberfest

#13 group-anagrams problem
  Cpp/group-anagrams/problem.md
  Cpp/group-anagrams/solution.cpp
Labels: good first issue, hacktoberfest

#9 added new problem with solution
  Cpp/Rotate-an-array-by-K/problem.md
  Cpp/Rotate-an-array-by-K/solution.cpp
Labels: good first issue, hacktoberfest

#14 Added problem 4Sum with solution in cpp
  Cpp/4Sum/problem.md
  Cpp/4Sum/solution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 add 0404-sum-of-left-leaves - LeetCode
  Py/0404-sum-of-left-leaves/problem.md
  Py/0404-sum-of-left-leaves/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#16 Added A Problem
  Java/Horses/problem.md
  Java/Horses/solution.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#17 Create Spiral Matrix solution
  Cpp/spiral_matrix/problem.md
  Cpp/spiral_matrix/solution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Added Trapping Rain Water problem
  Py/0042-trapping-rain-water/problem.md
  Py/0042-trapping-rain-water/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Added Dungeon Game problem
  Py/0174-dungeon-game/problem.md
  Py/0174-dungeon-game/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#24 add 2405-optimal-partition-of-string - LeetCode
  Py/2405-optimal-partition-of-string/problem.md
  Py/2405-optimal-partition-of-string/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#25 Add Reverse Linked List Problem
  Py/0206-reverse-linked-list/problem.md
  Py/0206-reverse-linked-list/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#27 15305-new-year-chaos-hackerank-medium
  Py/15305-new-year-chaos/problem.md
  Py/15305-new-year-chaos/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#28 Added sorting a linked list problem.
  Py/0148-sort-list/porblem.md
  Py/0148-sort-list/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#33 Added Reverse Nodes in k-Group
  Py/0025-reverse-nodes-in-k-group/problem.md
  Py/0025-reverse-nodes-in-k-group/solution.py
  Py/0061-rotate-list/problem.md
  Py/0061-rotate-list/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#34 I have added a cpp problem (koko Eating Bananas) which is rated medium on leetcode.
  Cpp/kokoEatingBananas/problem.md
  Cpp/kokoEatingBananas/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 Added Palindrome Linked List
  Py/0234-palindrome-linked-list/problem.md
  Py/0234-palindrome-linked-list/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#40 Added Largest Odd Number in String
  Cpp/1903-largest-odd-number-in-string/problem.md
  Cpp/1903-largest-odd-number-in-string/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#39 Problem/javascript
  Js/2605-Counter/problem.md
  Js/2605-Counter/solution.js
Labels: hacktoberfest, hacktoberfest-accepted

#44 Fire Again
  Cpp/Fire Again/Problem.md
  Cpp/Fire Again/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#45 Valid Parentheses
  Js/20-valid-parentheses/problem.md
  Js/20-valid-parentheses/solution.js
Labels: hacktoberfest, hacktoberfest-accepted

#46 Cpp solution for finding first and last position of an element in a s…
  Cpp/First_and_Last_Position_of_Element_in_Array/problem.md
  Cpp/First_and_Last_Position_of_Element_in_Array/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#47 Added Pow(x,n) | Leetcode-Medium | CPP & Python solution
  Cpp/0050-pow(x n)/problem.md
  Cpp/0050-pow(x n)/solution.cpp
  Py/0050-pow(x n)/problem.md
  Py/0050-pow(x n)/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#48 Rudolf and the Another Competition solved
  Cpp/Rudolf and the Another Competition/problem.md
  Cpp/Rudolf and the Another Competition/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Added Copy List with Random Pointer | Leetcode-Medium | Cpp & Python solution
  Cpp/0138-copy-list-with-random-pointer/problem.md
  Cpp/0138-copy-list-with-random-pointer/solution.cpp
  Py/0138-copy-list-wit-random-pointer/problem.md
  Py/0138-copy-list-wit-random-pointer/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 Added Generate Parenthesis | Leetcode-Medium | Cpp & Python solution
  Cpp/0022-generate-parentheses/problem.md
  Cpp/0022-generate-parentheses/solution.cpp
  Py/0022-generate-parenthesis/problem.md
  Py/0022-generate-parenthesis/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#59 Added Subsets problem | Leetcode-Medium | Cpp & Python solution
  Cpp/0078-subsets/problem.md
  Cpp/0078-subsets/solution.cpp
  Py/0078-subsets/problem.md
  Py/0078-subsets/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added Subsets-II | Leetcode-Medium | Cpp & Python solution
  Cpp/0090-subsets-II/problem.md
  Cpp/0090-subsets-II/solution.cpp
  Py/0090-subsets-II/problem.md
  Py/0090-subsets-II/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#51 Problem/codeforces chips on the board
  Cpp/Chips-on-the-board/problem.md
  Cpp/Chips-on-the-board/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#61 Made the changes requested, will close the other pull request
  Cpp/Top K Frequent Elements/problem.md
  Cpp/Top K Frequent Elements/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 two cpp problems
  Cpp/0896-monotonic-array/problem.md
  Cpp/0896-monotonic-array/solution.cpp
  Cpp/744-find-smallest-letter-greater-than-target/problem.md
  Cpp/744-find-smallest-letter-greater-than-target/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#65 Kitayuta's Colorful Graph
  Cpp/Kitayuta's Colorful Graph/Problem.md
  Cpp/Kitayuta's Colorful Graph/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Added Changes In README
  README.md
  images/logo.png
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#68 Added Remove Boxes Problem
  Cpp/0546-remove-boxes/problem.md
  Cpp/0546-remove-boxes/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#70 Add new javascript challenge
  Js/EventEmitter/problem.md
  Js/EventEmitter/solution.js
Labels: hacktoberfest, hacktoberfest-accepted

#69 Added problem Edit Distance with solution in CPP
  Cpp/edit-distance/problem.md
  Cpp/edit-distance/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 Euler
  Cpp/Euler/problem.md
  Cpp/Euler/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#73 new javascript problem called join two array by id
  Js/Join_2_arrays_by_Id/problem.md
  Js/Join_2_arrays_by_Id/solution.js
Labels: hacktoberfest, hacktoberfest-accepted

#75 Added Kth Missing Positive Number | Cpp & Python solution
  Cpp/1539-kth-missing-positive-number/problem.md
  Cpp/1539-kth-missing-positive-number/solution.cpp
  Py/1539-kth-missing-positive-number/problem.md
  Py/1539-kth-missing-positive-number/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 Dards
  Cpp/Dardos/problem.md
  Cpp/Dardos/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#79 Arraningcoin java problems added
  .vscode/launch.json
  Java/Arrangingcoin/problem.md
  Java/Arrangingcoin/solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#76 add new problem Sherlock and Divisors
  Py/2536-sherlock-and-divisors/problem.md
  Py/2536-sherlock-and-divisors/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#80 Added Split Array Largest Sum | Leetcode: Hard | Cpp & Python solution
  Cpp/410-split-array-largest-sum/problem.md
  Cpp/410-split-array-largest-sum/solution.cpp
  Py/410-split-array-largest-sum/problem.md
  Py/410-split-array-largest-sum/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#77 add diameter of a tree
  Cpp/Diameter of a tree/problem.md
  Cpp/Diameter of a tree/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#82 Add Median of Two Sorted Array | Leetcode: Hard | Cpp & Python solution
  Cpp/0004-median-of-two-sorted-array/problem.md
  Cpp/0004-median-of-two-sorted-array/solution.cpp
  Py/0004-median-of-two-sorted-array/problem.md
  Py/0004-median-of-two-sorted-array/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#81 add new problem flipping bits
  Py/5529-fliping-bits/problem.md
  Py/5529-fliping-bits/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#83 Beats 97.39% solution
  Cpp/edit-distance/solution2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#84 Longest Unequal Adjacent Groups Subsequence I
  Cpp/Longest Unequal Adjacent Groups Subsequence I/problem.md
  Cpp/Longest Unequal Adjacent Groups Subsequence I/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#85 Add another permutation problem
  Cpp/Another permutation problem/problem.md
  Cpp/Another permutation problem/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#88 Added Longest Consecutive Sequence | Leetcode: Medium | Cpp & Python solution
  Cpp/128-logest-consecutive-sequence/problem.md
  Cpp/128-logest-consecutive-sequence/solution.cpp
  Cpp/128-logest-consecutive-sequence/solution2.cpp
  Py/0128-longest-consecutive-sequence/problem.md
  Py/0128-longest-consecutive-sequence/solution.py
  Py/0128-longest-consecutive-sequence/solution2.py
Labels: hacktoberfest, hacktoberfest-accepted

#89 Create 347-Top K frequent Elements
  Cpp/347-Top K frequent Elements/problem.md
  Cpp/347-Top K frequent Elements/solutioon.cpp
  Cpp/785-Is Graph Bipartite/problem.md
  Cpp/785-Is Graph Bipartite/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#92 Create code.java
  Java/String to integer/problem.md
  Java/String to integer/solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#90 add new problem Manasa and Factorials
  Py/2301-manasa-and-factorials/problem.md
  Py/2301-manasa-and-factorials/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#93 add new problem Repeated String
  Py/24548-repeated-string/problem.md
  Py/24548-repeated-string/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#94 Added New problem of sortings in C++ language
  Cpp/Exams/problem.md
  Cpp/Exams/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#96 Added CPP problem
  Cpp/33_Search in Rotated Sorted Array/problem.md
  Cpp/33_Search in Rotated Sorted Array/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#97 Create solution-2.cpp
  Cpp/0546-remove-boxes/solution-2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#101 Added problem Largest Rectangle in Histogram with solution in cpp
  Cpp/largest-rectangle-in-histogram/problem.md
  Cpp/largest-rectangle-in-histogram/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#102 Added problem Dungeon Game with solution in cpp
  Cpp/dungeon-game/problem.md
  Cpp/dungeon-game/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#104 Added Binary Tree Level Order Traversal
  Cpp/102_Binary Tree Level Order Traversal/problem.md
  Cpp/102_Binary Tree Level Order Traversal/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#103 Patterns Problem in C++ Using For Loop
  Cpp/Different patterns in C++/Problem.md
  Cpp/Different patterns in C++/Solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#105 added new cpp problem
  Cpp/Dota2-senate/problem.md
  Cpp/Dota2-senate/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#106 Leetcode Valid Square Problem
  Py/593_Valid_Square/problem.md
  Py/593_Valid_Square/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#107 Added Majority Element-II | Subarray Sum Equal to K | Leetcode: Medium | CPP & Python solution
  Cpp/229-majority-element-II/problem.md
  Cpp/229-majority-element-II/solution.cpp
  Cpp/560-subarray-sum-equals-k/problem.md
  Cpp/560-subarray-sum-equals-k/solution.cpp
  Py/0229-majority-element-II/problem.md
  Py/0229-majority-element-II/solution.py
  Py/0560-subarray-sum-equal-k/problem.md
  Py/0560-subarray-sum-equal-k/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#109 Added solution to problem no. 315 from Leetcode in java
  Java/Count of Smaller Numbers After Self/problem.md
  Java/Count of Smaller Numbers After Self/solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#110 Project/going to cinema
  Cpp/going-to-cinema/problem.md
  Cpp/going-to-cinema/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#111 Added solution for backspace-string-compare
  Cpp/0844-backspace-string-compare/problem.md
  Cpp/0844-backspace-string-compare/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#112 Create solution for find-the-duplicate-number
  Cpp/0297-find-the-duplicate-number/problem.md
  Cpp/0297-find-the-duplicate-number/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#113 Create solution for design-hashmap
  Cpp/706-design-hashmap/problem.md
  Cpp/706-design-hashmap/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#114 Created solution for Leetcode's 1282th problem- Group People
  Cpp/1282-group-the-people-given-the-group-size-they-belong-to/problem.md
  Cpp/1282-group-the-people-given-the-group-size-they-belong-to/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#115 Implementing all Sorting Algorithm using cpp
  Cpp/Sorting Algorithm-Program/Problem.md
  Cpp/Sorting Algorithm-Program/Solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#116 Added a new question
  Java/Group Anagrams/Solution.java
  Java/Group Anagrams/problem.md
  Py/0026 Remove Duplicate from Sorted Array/Solution.py
  Py/0026 Remove Duplicate from Sorted Array/problem.md
Labels: hacktoberfest, hacktoberfest-accepted

#117 Goldbach conjecture
  .vscode/settings.json
  Cpp/goldbach_conjecture/problem.md
  Cpp/goldbach_conjecture/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#118 Add LeetCode 1008. Construct Binary Search Tree from Preorder Traversal
  Java/Construct Binary Search Tree from Preorder Traversal/Problem.md
  Java/Construct Binary Search Tree from Preorder Traversal/Solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#119 First Missing Positive
  Java/fmPositive/problem.md
  Java/fmPositive/solution.java
Labels: hacktoberfest, hacktoberfest-accepted

#122 Vertical Traversal of binary tree
  Cpp/987. Vertical Order Traversal of a Binary Tree/problem.md
  Cpp/987. Vertical Order Traversal of a Binary Tree/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#121 added roman problem
  Cpp/13-roman to integer/problem.md
  Cpp/13-roman to integer/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#123 Added the solution of Add two Numbers from LeetCode
  Py/0002.Add_Two_numbers/problem.md
  Py/0002.Add_Two_numbers/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#124 Added the Python Solutions of Reverse Integer in LeetCode
  Py/0007.Reverse_Integer/problem.md
  Py/0007.Reverse_Integer/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#125 Zigzag Level Order Traversal of Binary Tree
  Cpp/103. Binary Tree Zigzag Level Order Traversal/problem.md
  Cpp/103. Binary Tree Zigzag Level Order Traversal/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#126 Added the Python Solution of Q342 from LeetCode
  Py/0342.Power_of_Four/problem.md
  Py/0342.Power_of_Four/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#127 Added the Python Solution of 13. Roman to Integer from LeetCode
  Py/0013-Roman_to_Integer/problem.md
  Py/0013-Roman_to_Integer/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#131 645/Set-Mismatch for Python
  Py/645-Set-Mismatch/problem.md
  Py/645-Set-Mismatch/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#133 added new cpp problem
  Cpp/find-the-duplicate/problem.md
  Cpp/find-the-duplicate/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#132 Maximal Square Added
  Cpp/221-Maximal-Square/problem.md
  Cpp/221-Maximal-Square/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#138 Python solution added for Search in rotated sorted array
  Py/0033-search-in-rotated-sorted-array/problem.md
  Py/0033-search-in-rotated-sorted-array/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#139 Added CPP solution for Longest Palindromic Substring
  Cpp/005 Longest Palindromic Substring/problem.md
  Cpp/005 Longest Palindromic Substring/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#140 Sum of list 2
  Cpp/sum_of_list/problem.md
  Cpp/sum_of_list/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#141 Product of numbers
  Cpp/product_of_numbers/problem.md
  Cpp/product_of_numbers/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#144 Added a new frequently asked question
  Py/0004. Median of Two Sorted Arrays/problem.md
  Py/0004. Median of Two Sorted Arrays/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#145 triangular_number_sequence
  Cpp/triangular_number_sequence/problem.md
  Cpp/triangular_number_sequence/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#146 Added a new question
  Py/0232. Implement Queue using Stack/problem.md
  Py/0232. Implement Queue using Stack/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#148 Added the most important and frequently asked question
  Py/0141. Linked List Cycle/problem.md
  Py/0141. Linked List Cycle/solution.py
Labels: hacktoberfest, hacktoberfest-accepted

#149 Problems/cpp
  Cpp/Air-Quality-Index/problem.md
  Cpp/Air-Quality-Index/solution.cpp
  Cpp/Even-Coefficients/problem.md
  Cpp/Even-Coefficients/solution.cpp
  Cpp/Witua-and-maths/problem.md
  Cpp/Witua-and-maths/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#151 Add new problem
  Cpp/Two-Sum/problem.md
  Cpp/Two-Sum/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted
